name: High Performance Computing Group
author: University of Bristol
markdown: redcarpet
pygments: true
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      weight: 1
      layout: page